# Generated by Django 3.1.2 on 2021-01-08 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
