# Generated by Django 3.1.2 on 2021-01-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
