# Generated by Django 3.1.2 on 2021-01-16 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210111_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
